# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57c764304e85706eb75ff2251e1bd9ee9379f15d481bee174d0c445b7f530afe8b355677af1349366b57552c55ff0829737d16e5c6174d05c943a2b1d44a84dd

test:
  secret_key_base: df8cff9c796314ff70d7f801ed964834dc522bb62f2c7a4bf826ebc6901f0893cd99f19c15ee77e931fab3f9faabc8e21069357cb954ec914762a4edcc732a0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
